- creme/creme_core/models/custom_field.py
- creme/reports/core/report.py
- creme/reports/tests/core/test_report.py
- creme/reports/tests/test_graph.py
- creme/reports/tests/test_report.py
The export for some types of CustomField was broken (multi-enum) or no localized (datetime, bool, decimal).
Decimal are now localized in list-views too.
Aggregates are now localized in exported reports.
> Fix the export of CustomFields

- creme/billing/templates/billing/form/edit.html
- creme/creme_core/templates/creme_core/forms/entity-filter.html
- creme/creme_core/templates/creme_core/forms/header-filter.html
- creme/creme_core/templates/creme_core/generics/blockform/edit-wizard.html
- creme/creme_core/templates/creme_core/generics/blockform/edit.html
- creme/creme_core/templates/creme_core/generics/form/edit.html
- creme/persons/templates/persons/edit_contact_form.html
- creme/persons/templates/persons/edit_organisation_form.html
So quote chars were replaced by HTML crap.
It's because {% bloctrans .. asvar .. %} seems to not mark variable as safe.
> Some edition forms titles were escaped twice

- .circleci/config.yml
- Makefile
- setup.cfg
CircleCI: Update the python dependencies fetched from cache
Makefile: Remove the deprecated -rc isort argument
Makefile: compatibility - Add a format target
Dependencies: add ipython to the dev environment
Makefile: Fix karma-clean .PHONY 
Makefile: Do not remove creme.egg-info
CircleCI: use large ressource class for python tests
> Continuous integration improvement

- creme/mobile/tests/test_templatetags.py
TIP : `@skipIfNotInstalled` must be added AFTER `@parameterized.expand`
> Fix skipping of some mobile tests when geolocation is disabled.

- mediagenerator/filters/closure.py
- mediagenerator/filters/yuicompressor.py
- mediagenerator/generators/bundles/base.py
The purpose of this PR is displaying some context for each error like a `diff` output.
By default `yuicompressor` and `closure` just output line & column numbers of the HUGE concatened files and not useful at all.
I got this issue during the backport of the upgrade of tinymce on creme 2.1.
yuicompressor does not support usage of the keyword 'defaut' and displays
```
[ERROR] 75175:40:il manque un nom après un opérateur '.'
```
Now we have something a bit more interesting
```
ValueError: ______________________________________________
75173:     UnzonedRange.prototype.getStart = function () {
75174:         if (this.startMs != null) {
75175:             return moment_ext_1.default.utc(this.startMs).stripZone();
^__ il manque un nom après un opérateur '.'
75176:         }
75177: …
```
> Improve mediagenerator error output.

- creme/creme_core/forms/merge.py
In merge forms, the result inputs were not marked as required in HTML when they should.
> In merge forms, mark HTML inputs as required

- .circleci/.karma.conf.js
- .circleci/config.yml
- .karma.conf.js
- CHANGELOG.txt
- Makefile
- package.json
The new deployment mechanism on a separate directory needs some changes in the CI :
- Improving karma tools.
`--djangoStatics` : path to the compiled or packaged statics files served by django (default: `creme/media/statics`)
`--djangoSources` : root path to the tests files sources (default: `creme`)
`--coverageOutput` : directory of karma coverage output (default: `artifacts/karma_coverage`)
**Note**: Those arguments can be defines with the following environment variables:
`KARMA_DJANGOSTATICS`,  `KARMA_DJANGOSOURCES` & `KARMA_COVERAGEOUTPUT`
- Refactor circleci steps
> Fix CircleCI jobs for javascript linting & tests

- creme/creme_core/models/fields.py
- creme/creme_core/models/fields_config.py
- creme/creme_core/tests/models/test_fields_config.py
To allow the use of django's `dumpdata` and `loaddata` commands
> serialize FieldsConfig with primary natural_key

- CHANGELOG.txt
- creme/billing/bricks.py
- creme/billing/forms/line.py
- creme/billing/templates/billing/bricks/base/lines.html
- creme/billing/views/line.py
Target: v2.3-rc4
The purpose of these changes is to make easy to:
- Add a new Line type
- Override it's brick template and form
Changes:
- The template `billing/bricks/frags/line-fields.html` becomes a brick attribute
- Refactor the code of the formset needed for the line bricks and the `multi_save_lines` view into `creme.billing.forms.line.BaseLineEditFormset`
> Simplify billing document line forms overload

- .circleci/config.yml
- .coveragerc
- creme/creme_core/global_info.py
- setup.cfg
Use the new cimg CircleCI images.
Invalidate the venv cache.
No more ram variants for the database images, fallback to the standard images.
Most jobs use standard python images; javascript tests require browsers support.
Fix tag builds: `python37-tests-sqlite3` runs with tags.
> CircleCI: Legacy Convenience Image Deprecation trunk

- .circleci/config.yml
- creme/reports/views/report.py
The browsers variants images are still required because the generatemedia command needs a JVM.
Change the cache key: the former cached venv is not compatible
Manually setup browsers in the javascript tests job using the browsers orb
> CircleCI: Legacy Convenience Image Deprecation v2.2.12

- .circleci/config.yml
Twine relies on the cryptography package, which now depends on Rust to build.
To fetch a wheel and avoid building cryptography, we need an up-to-date version of pip.
> CI: creme-package job; Upgrade pip before installing twine;

- .circleci/config.yml
- creme/__init__.py
This pull request modifies the generated python cache key to include:
- a global prefix, to easily invalidate the cache
- the python version
- the `install-py-dev-env` `python` isn't required anymore and has been removed
- the creme version
- the setup.cfg hash for dependencies
Closes #389
> CI Improvements

- creme/creme_core/gui/pager.py
- creme/creme_core/tests/gui/test_pager.py
Cette PR corrige les quelques bugs que j'ai vu sur le pager ([là](https://demos.cremecrm.com/persons/organisation/4), [là](https://demos.cremecrm.com/persons/contact/13), et [là](https://demos.cremecrm.com/activities/activities?filter=&hfilter=activities-hf_activity&sort_key=regular_field-start&sort_order=DESC&selected_rows=&selection=multiple&q_filter=%7B%22op%22%3A%22AND%22%2C%22val%22%3A%5B%5D%7D&ct_id=77&search-regular_field-start-start=&search-regular_field-start-end=&search-regular_field-title=&search-relation-activities-object_participates_to_activity=&search-relation-activities-object_activity_subject=&search-regular_field-user=&search-regular_field-end-start=&search-regular_field-end-end=&search-regular_field-type=&search-regular_field-sub_type=&rows=10&page=4)):
- présence d'un …
> Fix a few pager bugs

- CHANGELOG.txt
- creme/geolocation/static/geolocation/js/geolocation.js
- creme/geolocation/static/geolocation/js/tests/addresses-brick.js
- creme/geolocation/static/geolocation/js/tests/geolocation-google.js
- creme/geolocation/static/geolocation/js/tests/geolocation.js
- creme/geolocation/static/geolocation/js/tests/persons-brick.js
It now includes the "content", the actual street/etc information, in addition to its owner and title.
Works similarly for Google Maps and OSM markers.
> Improve geolocation map markers' labels

- creme/creme_core/templates/creme_core/templatetags/widgets/help-sign.html
- creme/creme_core/tests/templatetags/test_creme_widgets.py
Hello,
little issue: The `icon` parameter in the templatetags [widget_help_sign](https://github.com/HybirdCorp/creme_crm/blob/main/creme/creme_core/templatetags/creme_widgets.py#L364) is not taking in account in the template of the widget and it's always the `info` icon instead.
I am not sure if I have to make an entry in the changelogs file for a so little change :) ?
Thanks !
> fix icon parameter in widget_help_sign

- CHANGELOG.txt
- creme/activities/models/activity.py
- creme/activities/tests/test_activity.py
> Since the relation 'subject of activity' is internal we need to remove them before deleting an Activity (backport 2.5.3)

- creme/assistants/tests/test_todo.py
- creme/creme_core/models/history.py
- creme/creme_core/tests/gui/test_history.py
- creme/creme_core/tests/models/test_history.py
It avoids creating 'auxiliary edition' line in some useless cases.
> Improve History code.

- creme/creme_config/tests/test_generics_views.py
- creme/creme_core/models/history.py
- creme/creme_core/tests/gui/test_history.py
- creme/creme_core/tests/models/test_history.py
**Issue:**
Currently, Creme `HistoryLine` check if a `ForeignKey` field has changed by comparing entities, so there is a DB request to get the old entity.
**Proposition:**
To avoid this request for each `ForeignKey` field, we can just compare the ids.
**Side effect 1:**
After this change, in `HistoryLine.modifications` property, we have `name_id` instead of `name`. 
For exemple: `['sector_id', sector01.id, sector02.id]` instead of `['sector', sector01.id, sector02.id]`
I tested the two versions by modifing a profile img and the history lines are displayed correctly before and after the change.
In the screen, the first modification hline is without the change and the second modification hline is with the change
I am not sure if it's a problem or not. 
**Side effect 2:**
The change of this …
> Refactor ForeignKey check on HistoryLine

- creme/creme_config/forms/creme_property_type.py
- creme/creme_config/tests/test_creme_property_type.py
Fix the creation of property types in creme_config: they were not marked as custom.
> Fix the creation of property types

- CHANGELOG.txt
- README.md
- creme/billing/exporters/latex.py
- creme/billing/templates/billing/export/latex/FR/fr_FR/clear/base.tex
- creme/billing/tests/test_export.py
- creme/settings.py
Thank you so much for making this software open source. I am still learning to use it and I am currently working on improving the LaTex backend to finally integrate Facture-X/Zugferd and Order-X into the billing backend.
I would  like to push those changes upstream as I progress if you are interested.
This PR starts with a small change to the LaTex backend replacing `pdflatex` with `lualatex` and `latexmk`. The latter has the following advantages over calling plain `pdflatex` or `lualatex`:
- `latexmk` will call tex multiple times if several passes are required by the tex engine.
- `latexmk` has the `-cd` flag which enters the temp directory during compilation and allows relative imports of auxiliary files like images (e.g. company logos or scanned signatures)
I chose to replace …
> Replace pdflatex with LuaLatex and latexmk

- creme/billing/migrations/0034_v2_6__fix_uuids.py
- creme/opportunities/migrations/0017_v2_6__fix_uuids.py
- creme/persons/migrations/0034_v2_6__fix_uuids.py
- creme/products/migrations/0015_v2_6__fix_categories_uuids.py
- creme/projects/migrations/0028_v2_6__fix_statuses_uuids.py
- creme/tickets/migrations/0015_v2_6__fix_uuids.py
The goal is to ease the uuid migration process for projects that declare static objects in code, or need to keep uuid consistants between multiple environment (i.e. local dev / staging / production)
> Creme 2.6 UUID migration mapping

- creme/creme_core/static/creme_core/js/forms.js
- creme/creme_core/static/creme_core/js/tests/form/forms.js
- creme/creme_core/static/creme_core/js/widgets/editor.js
- creme/creme_core/templates/creme_core/tests/test_frame.html
The editor is waiting for a 'submit' event from the Form element that never occurs in popups. Instead a new 'html5-pre-validate' event will be send to force editor.save() and fill the field.
> Fix empty tinymce field in popups.
