HybirdCorp/creme_crm

- CHANGELOG.txt
- creme/creme_core/core/entity_cell.py
- creme/creme_core/models/custom_field.py
- creme/creme_core/tests/core/test_entity_cell.py
- creme/creme_core/tests/views/test_creme_property.py
- creme/reports/core/report.py
Multi-enum are now renderered as <ul> for HTML.
> Improve the render of CustomFields in list-views & detail-views.

- creme/creme_core/management/commands/creme_populate.py
- setup.cfg
Regenerate Flake8 exceptions after removing activesync.
Fix flake8 E117: over-indented
> Fix flake8

- .githooks/pre-commit
- .githooks/pre-push
- .gitignore
- .karma.conf.js
- Makefile
> Add flake8 check hook & improve Makefile

- .circleci/circleci_settings.py
- .circleci/config.yml
- .circleci/mysql_settings.py
- .circleci/pgsql_settings.py
- .circleci/sqlite3_settings.py
- Setup locale within the containers:
Fix https://github.com/HybirdCorp/creme_crm/issues/10
- Run the tests with sqlite3
> CircleCI improvements

- creme/billing/forms/base.py
- creme/billing/templates/billing/bricks/billing-payment-information.html
- creme/billing/tests/test_invoice.py
- creme/billing/tests/test_payment_information.py
- creme/billing/urls.py
- creme/billing/views/payment_information.py
> Improvements on payment info

- creme/billing/forms/base.py
- creme/billing/forms/mass_import.py
- creme/billing/forms/templatebase.py
- creme/billing/models/base.py
- creme/billing/tests/test_app.py
- creme/billing/tests/test_line.py
- creme/billing/utils.py
- creme/documents/forms/folder.py
- creme/documents/locale/fr/LC_MESSAGES/django.po
- creme/documents/migrations/0001_initial.py
- creme/documents/models/folder.py
- creme/documents/tests/test_folder.py
- creme/opportunities/signals.py
- creme/opportunities/tests/test_billing.py
> Pre custom forms #05

- creme/billing/forms/quote.py
- creme/billing/signals.py
NB: it's about prospect workflow.
> Transform some code of form Quote into signal handler.

- .eslintignore
- .eslintrc
- creme/creme_config/bricks.py
- creme/creme_config/forms/button_menu.py
- creme/creme_config/forms/widgets.py
- creme/creme_config/locale/fr/LC_MESSAGES/django.po
- creme/creme_config/static/chantilly/creme_config/css/creme_config.css
- creme/creme_config/static/chantilly/creme_config/css/widgets.css
- creme/creme_config/static/creme_config/js/widgets.js
- creme/creme_config/static/icecream/creme_config/css/creme_config.css
- creme/creme_config/static/icecream/creme_config/css/widgets.css
- creme/creme_config/templates/creme_config/bricks/button-menu.html
- creme/creme_config/templates/creme_config/forms/widgets/buttonmenu-editor.html
- creme/creme_config/templates/creme_config/templatetags/buttons_placeholders.html
- creme/creme_config/templatetags/creme_config_tags.py
- creme/creme_config/tests/test_button_menu.py
- creme/creme_config/tests/test_widgets.py
- creme/creme_core/gui/button_menu.py
- creme/creme_core/static/creme_core/js/lib/Sortable/Sortable.js
- creme/settings.py
> Buttons config v2

- creme/reports/templates/reports/bricks/graph.html
- creme/settings.py
- ReportGraph brick
- email configuration
> Misc fixes

- CHANGELOG.txt
- creme/reports/templates/reports/bricks/graph.html
- creme/settings.py
- graph brick
- email settings
> Misc fiexes (version 2.2.2)

- creme/geolocation/management/commands/geolocation.py
fix geolocation stat command by supplying 'visible' argument to self.sysout()
> fix(management command) 'geolocation --stat' fix #232

- .circleci/config.yml
- setup.cfg
Automates the python package and the docker image build and upload
> Creme upload image and package

- creme/creme_core/forms/widgets.py
CreatorEntityfield is currently broken
> Fix MultiEntityCreatorWidget; shadowed name variable

- .circleci/config.yml
- .circleci/mysql_settings.py
- .circleci/pgsql_settings.py
- .circleci/sqlite3_settings.py
- creme/creme_core/utils/test.py
CI: move coverage into its own nightly worlflow
CI: Disable database migrations during tests
> CI: nightly coverage

- CHANGELOG.txt
- creme/creme_core/forms/fields.py
- creme/creme_core/tests/forms/test_json_fields.py
> Drop compatibility with old 'ctype' format in GenericEntityField

- creme/creme_core/core/enumerable.py
- creme/creme_core/enumerators.py
- creme/creme_core/forms/listview.py
- creme/creme_core/static/chantilly/creme_core/css/select2/select2-creme.css
- creme/creme_core/static/creme_core/js/list_view.core.js
- creme/creme_core/static/creme_core/js/tests/form/select2.js
- creme/creme_core/static/creme_core/js/widgets/dselect.js
- creme/creme_core/static/creme_core/js/widgets/form/select2.js
- creme/creme_core/static/icecream/creme_core/css/select2/select2-creme.css
- creme/creme_core/templates/creme_core/listview/search-widgets/enumerable.html
- creme/creme_core/templates/creme_core/listview/search-widgets/select.html
- creme/creme_core/templates/creme_core/tests/test_select2.html
- creme/creme_core/tests/core/test_enumerable.py
- creme/creme_core/tests/forms/test_listview.py
- creme/creme_core/tests/views/test_enumerable.py
- creme/creme_core/tests/views/test_listview.py
- creme/creme_core/tests/views/test_main.py
- creme/creme_core/views/enumerable.py
- creme/settings.py
> Add support for enumerable views in creme.form.Select2 widget

- creme/creme_core/static/creme_core/js/entity_cell.js
- creme/creme_core/static/creme_core/js/tests/widgets/checklistselect.js
- creme/creme_core/static/creme_core/js/tests/widgets/entitycells.js
- creme/creme_core/static/creme_core/js/widgets/checklistselect.js
> Ignore diacritics for item filtering in EntityCellsWidget & CheckListSelect

- CHANGELOG.txt
- creme/creme_config/forms/menu.py
- creme/creme_config/forms/user_role.py
- creme/creme_config/locale/fr/LC_MESSAGES/django.po
- creme/creme_config/tests/test_user_role.py
- creme/creme_config/views/menu.py
- creme/creme_core/models/menu.py
- creme/products/migrations/0001_initial.py
- creme/products/models/other_models.py
Configuration bricks, menu, custom-forms & search can be copied.
> Improve role cloning

- creme/reports/templates/reports/bricks/report-chart.html
> Use the same barchart color theme for both ReportChartBrick & ReportChartListBrick

- creme/creme_core/static/creme_core/js/tests/form/select2.js
- creme/creme_core/static/creme_core/js/widgets/form/select2.js
> Fix creme.form.Select2.refresh() to sync entries with new options

- creme/polls/tests/test_poll_reply.py
- creme/polls/views/poll_reply.py
> Polls : Fix 404 when going back on an already filled reply

- setup.cfg
The page-count bug of the previous versions has been fixed.
> Upgrade the version of 'xhtml2pdf' to <0.2.9>.

- CHANGELOG.txt
- Makefile
- creme/creme_core/core/entity_filter/operators.py
- creme/creme_core/forms/entity_filter/widgets.py
- creme/creme_core/forms/enumerable.py
- creme/creme_core/static/chantilly/creme_core/css/select2/select2-creme.css
- creme/creme_core/static/creme_core/js/widgets/form/select2.js
- creme/creme_core/static/icecream/creme_core/css/select2/select2-creme.css
- creme/creme_core/tests/core/entity_filter/test_operators.py
- creme/creme_core/tests/forms/test_entity_filter.py
- creme/creme_core/tests/forms/test_enumerable.py
- creme/creme_core/tests/views/test_entity_filter.py
- creme/creme_core/urls.py
- creme/creme_core/views/entity_filter.py
> Use EnumerableSelect for regular fields in entity filter form

- .circleci/config.yml
- creme/persons/tests/test_reports.py
- creme/reports/core/graph/hand.py
- creme/reports/static/icecream/reports/css/reports.css
- creme/reports/templates/reports/bricks/report-chart-list.html
- creme/reports/templates/reports/bricks/report-chart.html
- creme/reports/tests/test_graph.py
> Fix missing button that creates a report instance brick when there is no data

- CHANGELOG.txt
- creme/creme_core/static/chantilly/creme_core/css/popover.css
- creme/creme_core/static/icecream/creme_core/css/popover.css
- creme/reports/apps.py
- creme/reports/locale/fr/LC_MESSAGES/django.po
- creme/reports/report_chart_registry.py
- creme/reports/templates/reports/bricks/report-chart-list.html
- creme/reports/templates/reports/bricks/report-chart.html
- creme/settings.py
- creme/sketch/apps.py
- creme/sketch/bricks.py
- creme/sketch/static/chantilly/sketch/css/sketch.css
- creme/sketch/static/icecream/sketch/css/sketch.css
- creme/sketch/static/sketch/js/chart/barchart.js
- creme/sketch/static/sketch/js/chart/linechart.js
- creme/sketch/static/sketch/js/invert.js
- creme/sketch/static/sketch/js/sketch.js
- creme/sketch/static/sketch/js/tests/demo.js
- creme/sketch/static/sketch/js/tests/drawable.js
- creme/sketch/static/sketch/js/tests/invert.js
- creme/sketch/static/sketch/js/tooltip.js
- creme/sketch/static/sketch/js/utils.js
- creme/sketch/templates/sketch/bricks/chart.html
- creme/sketch/templates/sketch/bricks/line-chart.html
- creme/sketch/tests.py
TODO : Add links to listview on line dots
> New D3LineChart that draws a curved line

- creme/creme_core/forms/header_filter.py
- creme/creme_core/templates/creme_core/forms/widgets/entity-cells/widget.html
Fix header_filter preview; Enable complex field_printer html representations
> Fix header_filter preview;

- creme/creme_core/bricks.py
- creme/creme_core/gui/bricks.py
- creme/creme_core/models/bricks.py
- creme/creme_core/tests/base.py
- creme/creme_core/tests/gui/test_bricks.py
- creme/creme_core/tests/test_bricks.py
It fixes some issues with PostgreSQL too.
> Improve pagination of relationships & specific-relationship bricks.

- CHANGELOG.txt
- creme/activities/locale/fr/LC_MESSAGES/django.po
- creme/creme_config/bricks.py
- creme/creme_config/forms/user.py
- creme/creme_config/registry.py
- creme/creme_config/templates/creme_config/portals/bricks.html
- creme/creme_config/tests/test_registry.py
- creme/creme_core/templatetags/creme_core_tags.py
- creme/opportunities/bricks.py
- creme/opportunities/templates/opportunities/bricks/contacts.html
- creme/opportunities/templates/opportunities/bricks/managers.html
- creme/opportunities/templates/opportunities/bricks/products.html
- creme/opportunities/templates/opportunities/bricks/services.html
- creme/persons/apps.py
- creme/persons/buttons.py
- creme/persons/forms/contact.py
- creme/persons/locale/fr/LC_MESSAGES/django.po
- creme/persons/templates/persons/bricks/base/linked-people.html
- creme/persons/templates/persons/buttons/add-linked-contact.html
- creme/persons/templates/persons/buttons/contact-as-user.html
- creme/persons/tests/contact/test_transform_into_user.py
- creme/persons/tests/test_bricks.py
- creme/persons/urls.py
- creme/persons/views/contact.py
Notably button Contact => User
> Misc improvements for 2.6

- CHANGELOG.txt
- creme/billing/constants.py
- creme/billing/locale/fr/LC_MESSAGES/django.po
- creme/billing/migrations/0032_v2_6__statuses_is_default01.py
- creme/billing/migrations/0033_v2_6__statuses_is_default02.py
- creme/billing/models/credit_note.py
- creme/billing/models/invoice.py
- creme/billing/models/other_models.py
- creme/billing/models/sales_order.py
- creme/billing/models/templatebase.py
- creme/billing/populate.py
- creme/billing/tests/test_convert.py
- creme/billing/tests/test_credit_note.py
- creme/billing/tests/test_invoice.py
- creme/billing/tests/test_quote.py
- creme/billing/tests/test_sales_order.py
- creme/billing/views/base.py
- creme/billing/views/invoice.py
A field "InvoiceStatus.is_validated" has been added too.
> In 'billing', add fields "is_default" to status models.

- creme/creme_core/models/entity_filter.py
- creme/creme_core/models/header_filter.py
- creme/creme_core/tests/models/test_entity_filter.py
- creme/creme_core/tests/models/test_header_filter.py
Public filters could be edited/edited by user with no app permission.
> Fix permissions issue with EntityFilters & HeaderFilters.

- creme/creme_core/migrations/0104_v2_4__relation_object_ctype02.py
Optimisation de la migration creme_core 0104, qui prendrait environ 40 minutes sur une base de 5M de relations, itérativement réduite à ~2 minutes. Variations et résultats ci dessous:
```
def next_page(queryset):
return list(queryset[:2000])
def fill_object_ctype_v1(apps, schema_editor):
relations = apps.get_model("creme_core", "Relation").objects.select_related("object_entity")
for relation in tqdm(relations, total=relations.count()):
relation.object_ctype_id = relation.object_entity.entity_type_id
relation.save()
def fill_object_ctype_v2(apps, schema_editor):
Relation = apps.get_model("creme_core", "Relation")
base_queryset = Relation.objects.values("pk", "object_entity__entity_type_id").order_by("pk")
progress_bar = tqdm(total=base_queryset.count())
page = next_page(base_queryset) …
```
> Optimize migration creme_core 0104

- CHANGELOG.txt
- creme/creme_core/static/creme_core/js/tests/dialog/frame.js
- creme/creme_core/static/creme_core/js/widgets/dialog/frame.js
…ping tag when receiving json responses. Fix the detection regex to handle this case.
> Fix frame response detection for chrome (backport 2.4.15)

- creme/creme_core/static/creme_core/js/tests/ajax/backend.js
- creme/creme_core/static/creme_core/js/widgets/ajax/backend.js
Regression caused by the PR #771
> Fix issue cause by missing default traditional=true options in ajax backend

- creme/creme_config/tests/test_user_role.py
- creme/creme_core/tests/models/test_entity_filter.py
- creme/creme_core/utils/id_generator.py
The next step will be to use clean UUIDs
> Improve the generation of string IDs

- CHANGELOG.txt
- creme/creme_core/core/history.py
- creme/creme_core/models/history.py
- creme/creme_core/tests/core/test_function_field.py
- creme/creme_core/tests/core/test_history.py
> Enhance history state manipulations

- CHANGELOG.txt
- creme/creme_core/forms/fields.py
- creme/creme_core/forms/widgets.py
- creme/creme_core/models/fields.py
- creme/creme_core/tests/fake_models.py
- creme/creme_core/tests/forms/test_widgets.py
- creme/creme_core/tests/models/test_fields.py
> Field 'DatePeriodField' can now have a working 'default'
